version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

  # test:
  #   docker:
  #     - image: circleci/node:10-browsers
  #   steps:
  #     - checkout
  #     - run: <command>
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      # - test
